name: "assign_project"

on:
  issues:
    types:
      - opened

jobs:
  main:
    uses: roc-streaming/ci/.github/workflows/project_assign.yml@main
    with:
      project: 5
    secrets:
      triage-token: "${{ secrets.REPO_MANAGEMENT }}"
