name: "assign_project_columns"

on:
  issues:
    types:
      - labeled

permissions:
  pull-requests: write
  issues: write

jobs:
  main:
    uses: roc-streaming/ci/.github/workflows/project_assign_column.yml@main
    with:
      project: 5
      labeled: "help wanted"
      column: "Help wanted"
    secrets:
      triage-token: "${{ secrets.REPO_MANAGEMENT }}"
