name: "pr_opened"

on:
  pull_request_target:
    types:
      - opened
      - reopened

concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-set status labels
        uses: roc-streaming/ci/.github/workflows/pr_status_detect.yml@main

      - name: Auto-set contribution label
        uses: roc-streaming/ci/.github/workflows/pr_check_contrib.yml@main

      - name: Check linked issue
        uses: roc-streaming/ci/.github/workflows/pr_check_issue.yml@main

      - name: Check target branch
        uses: roc-streaming/ci/.github/workflows/pr_check_branch.yml@main
        with:
          base-branch: develop
