name: "pr_wip"

on:
  pull_request_target:
    types:
      - review_request_removed
      - converted_to_draft

concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: andymckay/labeler@1.0.4
        if: |
          github.event.pull_request.draft == true ||
          tojson(github.event.pull_request.requested_reviewers) == '[]'
        with:
          add-labels: 'status: work in progress'
          remove-labels: 'status: ready for review,status: needs revision'
