name: "triggers"

on:
  push:
    branches:
      - master

jobs:
  main:
    if: |
      github.repository_owner == 'roc-streaming'

    strategy:
      matrix:
        include:
          - repo: roc-go
            branch: main

          - repo: roc-java
            branch: main

          - repo: roc-pulse
            branch: main

          - repo: roc-vad
            branch: main

          - repo: rocd
            branch: main

          - repo: rt-tests
            branch: main

          - repo: roc-streaming.github.io
            branch: source

    name: ${{ matrix.repo }}

    runs-on: ubuntu-latest
    steps:
      - uses: roc-streaming/ci/.github/workflows/trigger_build.yml@main
        with:
          repo: ${{ matrix.repo }}
          branch: ${{ matrix.branch }}
